export enum QUERY_KEY {
    GET_ME = "get-me",
    CATEGORIES = "categories",
    BLOGS = "blogs",
    BLOG_DETAILS = "blog-details",
    HAS_LIKED = "has-liked",
    COUNT_LIKES = "count-likes",
    NOTIFICATIONS = "notifications",
    UNREAD_NOTIFICATION_COUNT = "unread-notification-count",
    PARENT_COMMENTS = "parent-comments",
    CHILD_COMMENTS = "child-comments",
    COUNT_COMMENTS = "count-comments",
    TOP_AUTHORS = "top-authors",
    TOP_CATEGORIES = "top-categories",
    WEB_VISIT_STATS = "web-visit-stats",
    BLOG_READ_STATS = "blog-read-stats",
    NEW_USER_STATS = "new-user-stats",
    NEW_BLOG_STATS = "new-blog-stats",
    ALL_AUTHORS = "all-authors",
    BLOGS_BY_USERNAME = "blogs-by-username",
    AUTHOR = "author"
}
