/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as AuthImport } from './routes/_auth'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSearchImport } from './routes/_layout/search'
import { Route as LayoutAuthenticatedImport } from './routes/_layout/_authenticated'
import { Route as LayoutAuthenticatedMeDashboardBlogsImport } from './routes/_layout/_authenticated/me/dashboard/blogs'

// Create Virtual Routes

const AuthSignupLazyImport = createFileRoute('/_auth/signup')()
const AuthSigninLazyImport = createFileRoute('/_auth/signin')()
const AuthResetPasswordLazyImport = createFileRoute('/_auth/reset-password')()
const LayoutBlogsBlogSlugLazyImport = createFileRoute(
  '/_layout/blogs/$blogSlug',
)()
const LayoutAuthorsUsernameLazyImport = createFileRoute(
  '/_layout/authors/$username',
)()
const LayoutAuthenticatedMeLazyImport = createFileRoute(
  '/_layout/_authenticated/me',
)()
const LayoutAuthenticatedBlogsCreateLazyImport = createFileRoute(
  '/_layout/_authenticated/blogs/create',
)()
const LayoutAuthenticatedMeSettingsProfileLazyImport = createFileRoute(
  '/_layout/_authenticated/me/settings/profile',
)()
const LayoutAuthenticatedMeSettingsPasswordLazyImport = createFileRoute(
  '/_layout/_authenticated/me/settings/password',
)()
const LayoutAuthenticatedBlogsBlogIdEditLazyImport = createFileRoute(
  '/_layout/_authenticated/blogs/$blogId/edit',
)()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const AuthSignupLazyRoute = AuthSignupLazyImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/signup.lazy').then((d) => d.Route))

const AuthSigninLazyRoute = AuthSigninLazyImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/signin.lazy').then((d) => d.Route))

const AuthResetPasswordLazyRoute = AuthResetPasswordLazyImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/reset-password.lazy').then((d) => d.Route),
)

const LayoutSearchRoute = LayoutSearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/search.lazy').then((d) => d.Route),
)

const LayoutAuthenticatedRoute = LayoutAuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutBlogsBlogSlugLazyRoute = LayoutBlogsBlogSlugLazyImport.update({
  id: '/blogs/$blogSlug',
  path: '/blogs/$blogSlug',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/blogs/$blogSlug.lazy').then((d) => d.Route),
)

const LayoutAuthorsUsernameLazyRoute = LayoutAuthorsUsernameLazyImport.update({
  id: '/authors/$username',
  path: '/authors/$username',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/authors/$username.lazy').then((d) => d.Route),
)

const LayoutAuthenticatedMeLazyRoute = LayoutAuthenticatedMeLazyImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => LayoutAuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_layout/_authenticated/me.lazy').then((d) => d.Route),
)

const LayoutAuthenticatedBlogsCreateLazyRoute =
  LayoutAuthenticatedBlogsCreateLazyImport.update({
    id: '/blogs/create',
    path: '/blogs/create',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_layout/_authenticated/blogs/create.lazy').then(
      (d) => d.Route,
    ),
  )

const LayoutAuthenticatedMeSettingsProfileLazyRoute =
  LayoutAuthenticatedMeSettingsProfileLazyImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => LayoutAuthenticatedMeLazyRoute,
  } as any).lazy(() =>
    import('./routes/_layout/_authenticated/me/settings/profile.lazy').then(
      (d) => d.Route,
    ),
  )

const LayoutAuthenticatedMeSettingsPasswordLazyRoute =
  LayoutAuthenticatedMeSettingsPasswordLazyImport.update({
    id: '/settings/password',
    path: '/settings/password',
    getParentRoute: () => LayoutAuthenticatedMeLazyRoute,
  } as any).lazy(() =>
    import('./routes/_layout/_authenticated/me/settings/password.lazy').then(
      (d) => d.Route,
    ),
  )

const LayoutAuthenticatedBlogsBlogIdEditLazyRoute =
  LayoutAuthenticatedBlogsBlogIdEditLazyImport.update({
    id: '/blogs/$blogId/edit',
    path: '/blogs/$blogId/edit',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_layout/_authenticated/blogs/$blogId.edit.lazy').then(
      (d) => d.Route,
    ),
  )

const LayoutAuthenticatedMeDashboardBlogsRoute =
  LayoutAuthenticatedMeDashboardBlogsImport.update({
    id: '/dashboard/blogs',
    path: '/dashboard/blogs',
    getParentRoute: () => LayoutAuthenticatedMeLazyRoute,
  } as any).lazy(() =>
    import('./routes/_layout/_authenticated/me/dashboard/blogs.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthenticatedImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchImport
      parentRoute: typeof LayoutImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupLazyImport
      parentRoute: typeof AuthImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_authenticated/me': {
      id: '/_layout/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof LayoutAuthenticatedMeLazyImport
      parentRoute: typeof LayoutAuthenticatedImport
    }
    '/_layout/authors/$username': {
      id: '/_layout/authors/$username'
      path: '/authors/$username'
      fullPath: '/authors/$username'
      preLoaderRoute: typeof LayoutAuthorsUsernameLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/blogs/$blogSlug': {
      id: '/_layout/blogs/$blogSlug'
      path: '/blogs/$blogSlug'
      fullPath: '/blogs/$blogSlug'
      preLoaderRoute: typeof LayoutBlogsBlogSlugLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_authenticated/blogs/create': {
      id: '/_layout/_authenticated/blogs/create'
      path: '/blogs/create'
      fullPath: '/blogs/create'
      preLoaderRoute: typeof LayoutAuthenticatedBlogsCreateLazyImport
      parentRoute: typeof LayoutAuthenticatedImport
    }
    '/_layout/_authenticated/me/dashboard/blogs': {
      id: '/_layout/_authenticated/me/dashboard/blogs'
      path: '/dashboard/blogs'
      fullPath: '/me/dashboard/blogs'
      preLoaderRoute: typeof LayoutAuthenticatedMeDashboardBlogsImport
      parentRoute: typeof LayoutAuthenticatedMeLazyImport
    }
    '/_layout/_authenticated/blogs/$blogId/edit': {
      id: '/_layout/_authenticated/blogs/$blogId/edit'
      path: '/blogs/$blogId/edit'
      fullPath: '/blogs/$blogId/edit'
      preLoaderRoute: typeof LayoutAuthenticatedBlogsBlogIdEditLazyImport
      parentRoute: typeof LayoutAuthenticatedImport
    }
    '/_layout/_authenticated/me/settings/password': {
      id: '/_layout/_authenticated/me/settings/password'
      path: '/settings/password'
      fullPath: '/me/settings/password'
      preLoaderRoute: typeof LayoutAuthenticatedMeSettingsPasswordLazyImport
      parentRoute: typeof LayoutAuthenticatedMeLazyImport
    }
    '/_layout/_authenticated/me/settings/profile': {
      id: '/_layout/_authenticated/me/settings/profile'
      path: '/settings/profile'
      fullPath: '/me/settings/profile'
      preLoaderRoute: typeof LayoutAuthenticatedMeSettingsProfileLazyImport
      parentRoute: typeof LayoutAuthenticatedMeLazyImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthResetPasswordLazyRoute: typeof AuthResetPasswordLazyRoute
  AuthSigninLazyRoute: typeof AuthSigninLazyRoute
  AuthSignupLazyRoute: typeof AuthSignupLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordLazyRoute: AuthResetPasswordLazyRoute,
  AuthSigninLazyRoute: AuthSigninLazyRoute,
  AuthSignupLazyRoute: AuthSignupLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LayoutAuthenticatedMeLazyRouteChildren {
  LayoutAuthenticatedMeDashboardBlogsRoute: typeof LayoutAuthenticatedMeDashboardBlogsRoute
  LayoutAuthenticatedMeSettingsPasswordLazyRoute: typeof LayoutAuthenticatedMeSettingsPasswordLazyRoute
  LayoutAuthenticatedMeSettingsProfileLazyRoute: typeof LayoutAuthenticatedMeSettingsProfileLazyRoute
}

const LayoutAuthenticatedMeLazyRouteChildren: LayoutAuthenticatedMeLazyRouteChildren =
  {
    LayoutAuthenticatedMeDashboardBlogsRoute:
      LayoutAuthenticatedMeDashboardBlogsRoute,
    LayoutAuthenticatedMeSettingsPasswordLazyRoute:
      LayoutAuthenticatedMeSettingsPasswordLazyRoute,
    LayoutAuthenticatedMeSettingsProfileLazyRoute:
      LayoutAuthenticatedMeSettingsProfileLazyRoute,
  }

const LayoutAuthenticatedMeLazyRouteWithChildren =
  LayoutAuthenticatedMeLazyRoute._addFileChildren(
    LayoutAuthenticatedMeLazyRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedMeLazyRoute: typeof LayoutAuthenticatedMeLazyRouteWithChildren
  LayoutAuthenticatedBlogsCreateLazyRoute: typeof LayoutAuthenticatedBlogsCreateLazyRoute
  LayoutAuthenticatedBlogsBlogIdEditLazyRoute: typeof LayoutAuthenticatedBlogsBlogIdEditLazyRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedMeLazyRoute: LayoutAuthenticatedMeLazyRouteWithChildren,
  LayoutAuthenticatedBlogsCreateLazyRoute:
    LayoutAuthenticatedBlogsCreateLazyRoute,
  LayoutAuthenticatedBlogsBlogIdEditLazyRoute:
    LayoutAuthenticatedBlogsBlogIdEditLazyRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAuthorsUsernameLazyRoute: typeof LayoutAuthorsUsernameLazyRoute
  LayoutBlogsBlogSlugLazyRoute: typeof LayoutBlogsBlogSlugLazyRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAuthorsUsernameLazyRoute: LayoutAuthorsUsernameLazyRoute,
  LayoutBlogsBlogSlugLazyRoute: LayoutBlogsBlogSlugLazyRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutAuthenticatedRouteWithChildren
  '/search': typeof LayoutSearchRoute
  '/reset-password': typeof AuthResetPasswordLazyRoute
  '/signin': typeof AuthSigninLazyRoute
  '/signup': typeof AuthSignupLazyRoute
  '/': typeof LayoutIndexRoute
  '/me': typeof LayoutAuthenticatedMeLazyRouteWithChildren
  '/authors/$username': typeof LayoutAuthorsUsernameLazyRoute
  '/blogs/$blogSlug': typeof LayoutBlogsBlogSlugLazyRoute
  '/blogs/create': typeof LayoutAuthenticatedBlogsCreateLazyRoute
  '/me/dashboard/blogs': typeof LayoutAuthenticatedMeDashboardBlogsRoute
  '/blogs/$blogId/edit': typeof LayoutAuthenticatedBlogsBlogIdEditLazyRoute
  '/me/settings/password': typeof LayoutAuthenticatedMeSettingsPasswordLazyRoute
  '/me/settings/profile': typeof LayoutAuthenticatedMeSettingsProfileLazyRoute
}

export interface FileRoutesByTo {
  '': typeof LayoutAuthenticatedRouteWithChildren
  '/search': typeof LayoutSearchRoute
  '/reset-password': typeof AuthResetPasswordLazyRoute
  '/signin': typeof AuthSigninLazyRoute
  '/signup': typeof AuthSignupLazyRoute
  '/': typeof LayoutIndexRoute
  '/me': typeof LayoutAuthenticatedMeLazyRouteWithChildren
  '/authors/$username': typeof LayoutAuthorsUsernameLazyRoute
  '/blogs/$blogSlug': typeof LayoutBlogsBlogSlugLazyRoute
  '/blogs/create': typeof LayoutAuthenticatedBlogsCreateLazyRoute
  '/me/dashboard/blogs': typeof LayoutAuthenticatedMeDashboardBlogsRoute
  '/blogs/$blogId/edit': typeof LayoutAuthenticatedBlogsBlogIdEditLazyRoute
  '/me/settings/password': typeof LayoutAuthenticatedMeSettingsPasswordLazyRoute
  '/me/settings/profile': typeof LayoutAuthenticatedMeSettingsProfileLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/search': typeof LayoutSearchRoute
  '/_auth/reset-password': typeof AuthResetPasswordLazyRoute
  '/_auth/signin': typeof AuthSigninLazyRoute
  '/_auth/signup': typeof AuthSignupLazyRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_authenticated/me': typeof LayoutAuthenticatedMeLazyRouteWithChildren
  '/_layout/authors/$username': typeof LayoutAuthorsUsernameLazyRoute
  '/_layout/blogs/$blogSlug': typeof LayoutBlogsBlogSlugLazyRoute
  '/_layout/_authenticated/blogs/create': typeof LayoutAuthenticatedBlogsCreateLazyRoute
  '/_layout/_authenticated/me/dashboard/blogs': typeof LayoutAuthenticatedMeDashboardBlogsRoute
  '/_layout/_authenticated/blogs/$blogId/edit': typeof LayoutAuthenticatedBlogsBlogIdEditLazyRoute
  '/_layout/_authenticated/me/settings/password': typeof LayoutAuthenticatedMeSettingsPasswordLazyRoute
  '/_layout/_authenticated/me/settings/profile': typeof LayoutAuthenticatedMeSettingsProfileLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/search'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/'
    | '/me'
    | '/authors/$username'
    | '/blogs/$blogSlug'
    | '/blogs/create'
    | '/me/dashboard/blogs'
    | '/blogs/$blogId/edit'
    | '/me/settings/password'
    | '/me/settings/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/search'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/'
    | '/me'
    | '/authors/$username'
    | '/blogs/$blogSlug'
    | '/blogs/create'
    | '/me/dashboard/blogs'
    | '/blogs/$blogId/edit'
    | '/me/settings/password'
    | '/me/settings/profile'
  id:
    | '__root__'
    | '/_auth'
    | '/_layout'
    | '/_layout/_authenticated'
    | '/_layout/search'
    | '/_auth/reset-password'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_layout/'
    | '/_layout/_authenticated/me'
    | '/_layout/authors/$username'
    | '/_layout/blogs/$blogSlug'
    | '/_layout/_authenticated/blogs/create'
    | '/_layout/_authenticated/me/dashboard/blogs'
    | '/_layout/_authenticated/blogs/$blogId/edit'
    | '/_layout/_authenticated/me/settings/password'
    | '/_layout/_authenticated/me/settings/profile'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_layout"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/reset-password",
        "/_auth/signin",
        "/_auth/signup"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/_authenticated",
        "/_layout/search",
        "/_layout/",
        "/_layout/authors/$username",
        "/_layout/blogs/$blogSlug"
      ]
    },
    "/_layout/_authenticated": {
      "filePath": "_layout/_authenticated.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/_authenticated/me",
        "/_layout/_authenticated/blogs/create",
        "/_layout/_authenticated/blogs/$blogId/edit"
      ]
    },
    "/_layout/search": {
      "filePath": "_layout/search.tsx",
      "parent": "/_layout"
    },
    "/_auth/reset-password": {
      "filePath": "_auth/reset-password.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/signin": {
      "filePath": "_auth/signin.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/signup": {
      "filePath": "_auth/signup.lazy.tsx",
      "parent": "/_auth"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/_authenticated/me": {
      "filePath": "_layout/_authenticated/me.lazy.tsx",
      "parent": "/_layout/_authenticated",
      "children": [
        "/_layout/_authenticated/me/dashboard/blogs",
        "/_layout/_authenticated/me/settings/password",
        "/_layout/_authenticated/me/settings/profile"
      ]
    },
    "/_layout/authors/$username": {
      "filePath": "_layout/authors/$username.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/blogs/$blogSlug": {
      "filePath": "_layout/blogs/$blogSlug.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/_authenticated/blogs/create": {
      "filePath": "_layout/_authenticated/blogs/create.lazy.tsx",
      "parent": "/_layout/_authenticated"
    },
    "/_layout/_authenticated/me/dashboard/blogs": {
      "filePath": "_layout/_authenticated/me/dashboard/blogs.tsx",
      "parent": "/_layout/_authenticated/me"
    },
    "/_layout/_authenticated/blogs/$blogId/edit": {
      "filePath": "_layout/_authenticated/blogs/$blogId.edit.lazy.tsx",
      "parent": "/_layout/_authenticated"
    },
    "/_layout/_authenticated/me/settings/password": {
      "filePath": "_layout/_authenticated/me/settings/password.lazy.tsx",
      "parent": "/_layout/_authenticated/me"
    },
    "/_layout/_authenticated/me/settings/profile": {
      "filePath": "_layout/_authenticated/me/settings/profile.lazy.tsx",
      "parent": "/_layout/_authenticated/me"
    }
  }
}
ROUTE_MANIFEST_END */
